name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.andaterra.com.br:21
        ftp-username: andaterrav001@andaterra.com.br
        ftp-password: zicaK7cu
    - name: Clean temp directory
      run: rm -rf *
      working-directory: temp
